In [1]:
import cv2
import numpy as np
import face_recognition
import os

In [2]:

path = 'ImagesAttendance'
images = []
classNames = []

myList = os.listdir(path)
print(myList)
for cl in myList:
    curImg = cv2.imread(f'{path}/{cl}')
    images.append(curImg)
    classNames.append(os.path.splitext(cl)[0])

print(classNames)

def findEncodings(images):
    encodeList = []
    for img in images:
        img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)
        encode = face_recognition.face_encodings(img)[0]
        encodeList.append(encode)
    return encodeList

encodeListKnown = findEncodings(images)
print("Encoding...")
print("Number of Images loaded: " + str( len(encodeListKnown)))
print("Endcoding Complete")

cap = cv2.VideoCapture(0)

while True:
    success, img = cap.read()
    imgSmall = cv2.resize(img,(0,0), None, 0.25,0.25)
    imgSmall = cv2.cvtColor(imgSmall, cv2.COLOR_RGB2BGR)

    facesCurFrame = face_recognition.face_locations(imgSmall)
    encodeCurFrame = face_recognition.face_encodings(imgSmall, facesCurFrame)

    for encodeFace,faceLoc in zip(encodeCurFrame, facesCurFrame):
        matches = face_recognition.compare_faces(encodeListKnown, encodeFace)
        faceDis = face_recognition.face_distance(encodeListKnown, encodeFace)
        print(faceDis)
        matchIndex = np.argmin(faceDis)

        if matches[matchIndex]:
            name = classNames[matchIndex].upper()
            print(name)
            y1,x2,y2,x1 = faceLoc
            y1, x2, y2, x1 =  y1*4,x2*4,y2*4,x1*4
            cv2.rectangle(img, (x1,y1),(x2,y2), (0,255,0),2)
            cv2.rectangle(img,(x1,y2-35),(x2,y2),(0,255,0),cv2.FILLED)
            cv2.putText(img, name, (x1+6,y2-6),cv2.FONT_HERSHEY_COMPLEX,1,(255,255,255),2)



    cv2.imshow('Webcam', img)
    cv2.waitKey(1)


['Dylan.jpg', 'Connor Packham.png', 'Ben Cullen.png', 'Ben Graff.png']
['Dylan', 'Connor Packham', 'Ben Cullen', 'Ben Graff']
Encoding...
Number of Images loaded: 4
Endcoding Complete


2023-11-02 17:23:30.415 python[2631:26039] WARNING: AVCaptureDeviceTypeExternal is deprecated for Continuity Cameras. Please use AVCaptureDeviceTypeContinuityCamera and add NSCameraUseContinuityCameraDeviceType to your Info.plist.


[0.51485172 0.61484023 0.69737315 0.74286264]
DYLAN
[0.54721792 0.62807419 0.71670794 0.76811873]
DYLAN
[0.56186761 0.64725174 0.73043426 0.77491543]
DYLAN
[0.52290405 0.62827315 0.69068747 0.76715579]
DYLAN
[0.51042377 0.64364498 0.70984835 0.78172286]
DYLAN
[0.51147038 0.64505163 0.72048223 0.78303694]
DYLAN
[0.51975265 0.6440224  0.7187337  0.78568612]
DYLAN
[0.51942844 0.63903374 0.72750822 0.79239178]
DYLAN
[0.51670197 0.6396054  0.71739088 0.79809032]
DYLAN
[0.50249267 0.63629855 0.72547382 0.80305575]
DYLAN
[0.49191875 0.63988584 0.71954524 0.79210436]
DYLAN
[0.47677954 0.63225023 0.73305959 0.83799953]
DYLAN
[0.53197219 0.6597884  0.69110931 0.78300494]
DYLAN
[0.49527735 0.62957707 0.68716623 0.77859438]
DYLAN
[0.50410839 0.63138586 0.6887178  0.79630308]
DYLAN
[0.52441031 0.65407108 0.67172838 0.81040224]
DYLAN
[0.52655549 0.65164709 0.68576426 0.80221642]
DYLAN
[0.51462543 0.66897188 0.67717741 0.82965023]
DYLAN
[0.53196652 0.67237308 0.67131118 0.81397206]
DYLAN
[0.52939222 

KeyboardInterrupt: 